M48
; DRILL file {KiCad 8.0.6} date 2025-02-08T19:38:09+0000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-08T19:38:09+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0591
%
G90
G05
T1
X4.6248Y-3.3303
X4.6559Y-3.5047
T2
X4.6457Y-3.1693
X4.9213Y-3.2106
M30
